name = "acm-dev"
main = "src/worker.tsx"
compatibility_date = "2023-08-21"

[site]
bucket = "./assets"

[[d1_databases]]
binding = "DB" # i.e. available in your Worker on env.DB
database_name = "acm-dev-2"
database_id = "b06c177b-2fbe-4763-b0ac-699dd5688e79"
preview_database_id = "b06c177b-2fbe-4763-b0ac-699dd5688e79"
